---
{{- range $name, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
spec:
  selector:
    app: {{ $name }}
  ports:
    - name: {{ $name }}-port
      protocol: TCP
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
  type: ClusterIP

---
{{- end }}