apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - namespace/namespace.yaml

  - postgres/service.yml
  - postgres/statefulset.yml

  - frontend-service/deployment.yml
  - frontend-service/service.yml

  - medicine-service/deployment.yml
  - medicine-service/service.yml

  - order-service/deployment.yml
  - order-service/service.yml


  - user-service/deployment.yml
  - user-service/service.yml

  - ingress/ingress.yml
  